### ISSUE TITLE
No faces found on the image error

### ISSUE THREAD

**Issue by kowalgregy** [Inferencer/LipSick#19]
Thanks for working on this potentially amazing project. I tried the tool through Google Colab and got the error in the title. Are there any particular requirements for the video resolution, quality, etc.?

**Comment by Inferencer** [comment]
I will try an code something by tomorrow that skips frames where no faces are found its not complicated to do. its a common problem amongst tools with landmark detectors it often stems from a single frame at the start of end of the video, it's guessing what the user wants for that particular video is the problem..
for example if no frames are found in frame 26 do we loop the video up until that point or do we keep skipping frames until we find more faces and if we do find more frames with faces to we start using those frames as the video instead of the starting frames which means we have to edit custom frames again and that's just one example I can think of at least 3 more

The Google Colab is rather old now so I will look at updating that to include the features of the local installation, best input would be 1920x1080 but It does work with the majority of sizes. There is a few lines of code that currently do video conversion that could be optimized to be honest but I can do an option for speed vs quality and I have just found out the face tracker might not be using GPU currently (I'm just thinking out loud at this point) point is I need some sleep but it shall be done 

..also if you want you can send me the video file with no face detected error and I can edit it for you so the bad frames are gone.

**Comment by Ex3cutionerX** [comment]
I'm running it locally and get the same error: ValueError: No faces found in the frame. tried multiple videos with crystal clear face subjects. Can you help?

**Comment by Azemblage** [comment]
Hi There!

Any update on this? Still appearing the same 

  raise ValueError("No faces found in the image.")
  
  
  And the video has face always and well lighted.
  
  Is there something might be doing wrong is there a tutorial ? To better make it work on colab?

**Comment by HerzogVonWiesel** [comment]
Having the same issue. Is there any progress on this?

**Comment by Inferencer** [comment]
no progress sorry so if i make the alignments and landmarks detection better then people will use the wrong types of vids 

for now im just recommending this repo, although its portrait animation its sota and worth discontinuing this project for
https://github.com/KwaiVGI/LivePortrait
