### ISSUE TITLE
Model changing tone of original video

### ISSUE THREAD

**Issue by kalpesh-maru** [Inferencer/LipSick#6]
After the original frame is passed through the model the skin tone appears to be a little darker.

**Comment by Inferencer** [comment]
As it's a generalized model the majority of the datasets used in training was a little darker that real world scenarios, there was a portion that was a little lighter, for a quick fix you can try "shot matching" the lighting using a video editor or using a darker video although changing the contrast wouldn't have much of an effect, the model does work best with warm studio lighting.

https://github.com/Inferencer/LipSick/assets/121839197/3e4f844b-0e97-4633-adbc-1e7609563868

**Comment by kalpesh-maru** [comment]
Actually, what I am doing is I am using a model (video) with closed mouth as base and lip Syncing it with DINET, I am detecting silence in mel-spectogram and replacing the model output frame with original frame upon silence, I am doing this because the model output has not complete closed mouth upon silence which makes it less realistic, but since model output (pred) frame is a bit dull then original, Video becomes flashy since original frames I am replacing are brighter. I want the original and model output to have same color config. Do you have any suggestions for this.

**Comment by Inferencer** [comment]
Based on previous random tests where I kept changing things to understand the code I know there is something you can edit in deepspeech.py to achieve mouth fully closed I will do some tests later to figure out what value needs to be edited, then you could use that as your base.

If that's an acceptable approach we can look at the best workflow that would also allow high teeth fidelity on speaking, as just lip-syncing a mouth closed would yield poorer results due to to DINet not being able to use teeth in the reference images. 

Although when doing all of this.. if at the end you will be having silent frames with mouth closed there will be a slight glitch look where the mouth goes from initially being open to immediately being closed so wouldn't be as smooth.

**Comment by kalpesh-maru** [comment]
For smoothness, I can simply interpolate the frames from original closed mouth to prediction from model to get mid frames to make it smooth. I will look into deepspech.py and try understanding the code

**Comment by Inferencer** [comment]
Another approach could be to print the file deepspeech is producing as a CSV which will be the mouth coordination values and change the values then set it to use that file instead of generating its own in the next run.
I'm not sure what format it expects or if it would be ok to set all the values to zero but might be worth a shot, I haven't learned Mel spectrums yet so I'm limited on the options I can suggest.

**Comment by kalpesh-maru** [comment]
I was finally able to solve this, After using many techniques like color transfer and blending it did not work as expected, I followed up on your suggestion and make the deepspeech op to 0 which gave me closed mouth from model.

if is_silence:
            tensor = np.zeros_like(ds_feature_padding[clip_end_index - 5: clip_end_index, :])
        else:
            tensor = ds_feature_padding[clip_end_index - 5: clip_end_index, :]
        deepspeech_tensor = (
            torch.from_numpy(
               tensor)
            .permute(1, 0)
            .unsqueeze(0)
            .float()
            .cuda()
        )
      I added this line making the tensor 0 when there is silence.

**Comment by Inferencer** [comment]
Great work I'll add this to things to implement as updates.

**Comment by Inferencer** [comment]
In relation to skin tone I have continued the conversation in another issue
https://github.com/Inferencer/LipSick/issues/8#issuecomment-2099653644

**Comment by Inferencer** [comment]
> I was finally able to solve this, After using many techniques like color transfer and blending it did not work as expected, I followed up on your suggestion and make the deepspeech op to 0 which gave me closed mouth from model.
> 
> if is_silence: tensor = np.zeros_like(ds_feature_padding[clip_end_index - 5: clip_end_index, :]) else: tensor = ds_feature_padding[clip_end_index - 5: clip_end_index, :] deepspeech_tensor = ( torch.from_numpy( tensor) .permute(1, 0) .unsqueeze(0) .float() .cuda() ) I added this line making the tensor 0 when there is silence.

How did you define silence, was about to implement this as an option but realized it wasn't complete , just re-read your comment in melspectrum and original frame so thats why it was closing fast wouldnt it be better to change the audio landmarks generated by deepspeech?

**Comment by kalpesh-maru** [comment]
> > I was finally able to solve this, After using many techniques like color transfer and blending it did not work as expected, I followed up on your suggestion and make the deepspeech op to 0 which gave me closed mouth from model.
> > if is_silence: tensor = np.zeros_like(ds_feature_padding[clip_end_index - 5: clip_end_index, :]) else: tensor = ds_feature_padding[clip_end_index - 5: clip_end_index, :] deepspeech_tensor = ( torch.from_numpy( tensor) .permute(1, 0) .unsqueeze(0) .float() .cuda() ) I added this line making the tensor 0 when there is silence.
> 
> How did you define silence, was about to implement this as an option but realized it wasn't complete


I was able to detect silence using pydub

from pydub import AudioSegment

def detect_silence_pydub(audio):
    audio_segment = AudioSegment.from_wav(audio)
    silence_segments = detect_silence(
        audio_segment, min_silence_len=500, silence_thresh=-40)
    array = []
    for i, (start, end) in enumerate(silence_segments):
        array.append({"start":  math.ceil(start / 1000.0),
                     "end": round(end / 1000.0, 2)})
    return array
